spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    username: yassine
    password: laamiri
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:exam
